### ISSUE TITLE
can I use gnmatcher to match two local lists?

### ISSUE THREAD

**Issue by abubelinha** [gnames/gnmatcher#39]
I am just wondering if gnmatcher is the right tool to use (**offline**) for this purpose:

I have two lists of scientific names, and I want to produce a 3rd list of matches. 
- List1 is just "correct" (i.e., an already curated national checklist with 50000 names).
- List2 contains about 4000 names expected to be in List1, but they could contain mispellings.
I just want to compare names in List2 against those in List1, and receive this back:
- List3 of 4000 items (either correct names as they matched from List1, or "couldn't match" flags). 
I suppose the program has to be feeded with List1, List2 and also with a numeric parameter (minimum percentage of similarity required for a positive match, or something like that).

Example:

| master list (L1): |
| ------------- |
| Homo sapiens L. |
| Felis catus L. |
| Canis familiaris L. |
| Canis lupus L. |
| Sus domesticus Erxleben |
| Sus scrofa L. |
| Ovis aries L. |
| Bos taurus L. |
| Panthera leo |
| Gallus gallus L. |
| Equus asinus L. |
| Apis mellifera L. |
| Anas platyrhynchos L. |

| names to match (L2) | ==> matcher(L1, L2, min=0.9) ==> | matches (L3) |
| :------------- | :-------------: | :------------- |
| Bos taurus Linn. | ==> | **Bos taurus L.** |
| Gallus asinus | ==> | _couldn't match_ |
| Momo sapiens | ==> | **Homo sapiens L.** |
| Sus domesticus L. | ==> | _couldn't match_ |

I would like to use Python system calls (Windows OS) to pass the lists and other parameters and receive back results.

Is gnmatcher (or any other gnames software) a good choice for doing this?
If not, could you recommend another options?

The main thing here is that I want to reconcile a list of (possibly misspelled) names against my own-curated list (not against any web services).

I suppose this is not difficult to implement in pure Python using some kind of fuzzy string matching library.
But I am already calling other gnames tools from Python (i.e. gnparser is returning results really fast). 
So I thought it could be possible to find a tool which I can call for doing this task the same way.

**Comment by dimus** [comment]
The best would be if a dataset is already in gnverifier data-sources, than you just use something like 

    gnverifier -s {id of the source} -o file_with_second_source

I guess gnmatcher can be used too, if you do:

Match source1 to gnmatcher
Match source2 to gnmatcher

Collect shared matches as a match of source1 to source2

**Comment by abubelinha** [comment]
Yes indeed, but I was talking about a "personal" dataset, like a curated museum database list of names. 
I say "personal" not in the sense that it is private, but I don't think it could ever be in gnverifier because nobody else would be interested in using it.

So my interest is matching names of new specimens entering the collection, to check if their names have already been used.
As I understand, none of your suggestions would work offline, right?
I had doubts if gnmatcher could serve for this purpose, assuming that I could feed it with my own database and nothing else.

But I still have not clear if gnmatcher depends on accessing globalnames website or not? 
This sentence makes me feel it does not: "_You will need PostgreSQL with a restored dump of gnames database_".
But as I said, I would be interested in using it just to match names against my own database, and then let LAN clients to connect it. Is this possible?

**Comment by dimus** [comment]
Yes, I think eventually gnregistry will materialize. My idea for it is to let anybody to create a resource, that they can reimport back into their local gnverifier. But to make their resource available at the gn site they would need to mark it so, and wait for approval from GN. After that it would be harvested automatically.

It is a vision, that would require significant work sometime in the future. I would say making registry like this would take as much time as making the gnverifier ecosystem - 1-2 years of a programmer's undivided attention.

**Comment by dimus** [comment]
Check out https://github.com/gnames/gndiff let me know if it fits your needs, and what is missing. It is fresh out of the owen, so it is 'slowish'. It keeps all data in memory, so too big data-sets might create a problem. I was able to compare 300,000 names list against 1million names list in about 2min, eating 6Gb of memory. I would say that tradeoffs for the future development will depend on accumulated usecases.
